services:
    AppBundle\Menu\MenuBuilder:
        class: AppBundle\Menu\MenuBuilder
        arguments:
            - "@knp_menu.factory"

        tags:
            -
                name: knp_menu.menu_builder
                method: createMainMenu
                alias: main

    AppBundle\Form\Extension\NoRequiredDefaultExtension:
        class: AppBundle\Form\Extension\NoRequiredDefaultExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FileType }
